threebrs_admin_docs_plugin_index:
    path: /docs
    controller: ThreeBRS\SyliusDocsPlugin\Controller\DocsController::index
    methods: [GET]

threebrs_admin_docs_plugin_show:
    path: /docs/{slug}
    controller: ThreeBRS\SyliusDocsPlugin\Controller\DocsController::show
    methods: [GET]
    requirements:
        slug: '[a-zA-Z0-9_\-]+'

threebrs_admin_docs_plugin_image:
    path: /docs/doc/{filename}
    controller: ThreeBRS\SyliusDocsPlugin\Controller\DocsController::image
    methods: [GET]
    requirements:
        filename: '.+'


        
