threebrs_sylius_documentation_admin_index:
    path: /documentation
    controller: ThreeBRS\SyliusDocumentationPlugin\Controller\DocumentationController::index
    methods: [ GET ]

threebrs_sylius_documentation_admin_show:
    path: /documentation/{slug}
    controller: ThreeBRS\SyliusDocumentationPlugin\Controller\DocumentationController::show
    methods: [ GET ]
    requirements:
        slug: '[a-zA-Z0-9_\-]+'

threebrs_sylius_documentation_admin_image:
    path: /documentation/document/{filename}
    controller: ThreeBRS\SyliusDocumentationPlugin\Controller\DocumentationController::image
    methods: [ GET ]
    requirements:
        filename: '.+'
