services:
    _defaults:
        autowire: false
        autoconfigure: false

    ThreeBRS\SyliusDocumentationPlugin\Menu\AdminMenuListener:
        arguments:
            - '@translator'
        tags:
            - { name: kernel.event_subscriber }

    League\CommonMark\CommonMarkConverter: ~

    ThreeBRS\SyliusDocumentationPlugin\Controller\DocumentationController:
        public: true
        arguments:
            - '@twig'
            - '@League\CommonMark\CommonMarkConverter'
            - '%threebrs_sylius_documentation.docs_path%'
            - '%kernel.project_dir%'
            - '@router'
